name: teslo_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  animate_do: ^3.3.4
  dio: ^5.0.3
  expansion_tile_card: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_math_fork: ^0.7.2
  flutter_riverpod: ^2.3.2
  font_awesome_flutter: ^10.7.0
  formz: ^0.5.0+1
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  remixicon: ^1.2.0
  riverpod_annotation: ^2.5.3
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
